"""empty message

Revision ID: 63835b4801ac
Revises: a3f928c1a323
Create Date: 2020-04-30 19:58:01.789274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63835b4801ac'
down_revision = 'a3f928c1a323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
